/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/lukewen/heron_ws/src/heron/heron_msgs/msg/Helm.msg
 *
 */


#ifndef HERON_MSGS_MESSAGE_HELM_H
#define HERON_MSGS_MESSAGE_HELM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heron_msgs
{
template <class ContainerAllocator>
struct Helm_
{
  typedef Helm_<ContainerAllocator> Type;

  Helm_()
    : thrust(0.0)
    , yaw_rate(0.0)  {
    }
  Helm_(const ContainerAllocator& _alloc)
    : thrust(0.0)
    , yaw_rate(0.0)  {
    }



   typedef float _thrust_type;
  _thrust_type thrust;

   typedef float _yaw_rate_type;
  _yaw_rate_type yaw_rate;




  typedef boost::shared_ptr< ::heron_msgs::Helm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heron_msgs::Helm_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Helm_

typedef ::heron_msgs::Helm_<std::allocator<void> > Helm;

typedef boost::shared_ptr< ::heron_msgs::Helm > HelmPtr;
typedef boost::shared_ptr< ::heron_msgs::Helm const> HelmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heron_msgs::Helm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heron_msgs::Helm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace heron_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'heron_msgs': ['/home/lukewen/heron_ws/src/heron/heron_msgs/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::heron_msgs::Helm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heron_msgs::Helm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heron_msgs::Helm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heron_msgs::Helm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heron_msgs::Helm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heron_msgs::Helm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heron_msgs::Helm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2d59470d537e1bf55bc57a5005f3cd5";
  }

  static const char* value(const ::heron_msgs::Helm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2d59470d537e1bfULL;
  static const uint64_t static_value2 = 0x55bc57a5005f3cd5ULL;
};

template<class ContainerAllocator>
struct DataType< ::heron_msgs::Helm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heron_msgs/Helm";
  }

  static const char* value(const ::heron_msgs::Helm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heron_msgs::Helm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Command a percentage amount of total thrust capacity, and an turn rate.\n\
# On a conventional craft, turn rate would map to rudder.\n\
\n\
# Thrust amount ranges from [-1.0..1.0], where 1.0 pushes Heron forward.\n\
float32 thrust\n\
\n\
# Yaw rate specified in radians/sec, where positive values cause Heron\n\
# to turn toward the port deck. The controller will use feedback from the\n\
# IMU's gyroscopes to attempt to match the command rate.\n\
float32 yaw_rate\n\
\n\
";
  }

  static const char* value(const ::heron_msgs::Helm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heron_msgs::Helm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.thrust);
      stream.next(m.yaw_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Helm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heron_msgs::Helm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heron_msgs::Helm_<ContainerAllocator>& v)
  {
    s << indent << "thrust: ";
    Printer<float>::stream(s, indent + "  ", v.thrust);
    s << indent << "yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERON_MSGS_MESSAGE_HELM_H
